filebeat.inputs:
  - type: log
    paths:
      - /usr/share/filebeat/logs/*.json
    json.keys_under_root: true
    json.add_error_key: true

output.elasticsearch:
  hosts: ["http://localhost:9200"]
  username: "elastic"
  password: "YOUR_PASSWORD"
